import './globals.css'
import type { Metadata } from 'next'
import { Inter, Montserrat } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const montserrat = Montserrat({ subsets : ['latin'] })

export const metadata: Metadata = {
  title: 'Payment Splitting App || Powered by ZBD',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
} ) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} py-20 px-80 bg-blue`}>{children}</body>
    </html>
  )
}
